apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: crossplane-contrib-function-auto-ready
spec:
  package: 'gitlab-registry.insee.fr/kubernetes/kubeqfapp/poc/crossplane/crossplane-contrib/function-auto-ready:v0.7.0'
  packagePullSecrets:
    - name: registry-gitlab-insee-fr-pull-secret