spring.application.name=exemple-kube
environnement=local

#===================================================================#
# SPRING BOOT ACTUATOR  											#
#===================================================================#
# permet de changer le base-path /actuator pour que ce soit à la racine
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,info,metrics
# activation des endpoints liveness et readiness
management.endpoint.health.probes.enabled=true
# activation des informations dans /info
management.info.env.enabled=true
# permet de changer l'URL de /health en /healthcheck
management.endpoints.web.path-mapping.health=healthcheck
# voir les détails du service health
management.endpoint.health.show-details=always
# divers
management.info.env.enabled=true
management.info.java.enabled=true
