#===================================================================#
# CONFIGURATION DES LOG										        #
#===================================================================#
# Coloration syntaxique des log
spring.output.ansi.enabled=ALWAYS
# Gestion des logs avec LOGBACK
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.fr.insee=DEBUG

#===================================================================#
# DIVERS            										        #
#===================================================================#
# Permet d'afficher le message d'erreur dans le response body
spring.web.error.include-message=always
# activation de la compression des réponses HTTP
server.compression.enabled=true
# Taille maximale d'un fichier unique
spring.servlet.multipart.max-file-size=10MB
# Taille maximale de la requête totale (incluant plusieurs fichiers et d'autres données)
spring.servlet.multipart.max-request-size=10MB

#===================================================================#
# SPRING BOOT ACTUATOR  											#
#===================================================================#
# permet de changer le base-path /actuator pour que ce soit à la racine
management.endpoints.web.base-path=/
management.endpoints.web.exposure.include=health,info,metrics
# activation des endpoints liveness et readiness
management.endpoint.health.probes.enabled=true
# activation des informations dans /info
management.info.env.enabled=true
# permet de changer l'URL de /health en /healthcheck
management.endpoints.web.path-mapping.health=healthcheck
# voir les détails du service health
management.endpoint.health.show-details=always
# divers
management.info.env.enabled=true
management.info.java.enabled=true
##### Gestion du endpoint /info #####
info.versionApplication=@project.version@
info.javaVersion=${java.version}
info.nomApplication=@project.name@
info.descApplication=@project.description@
# info.datasourceUrl=${spring.datasource.url}
# affichage dans Swagger des endpoints d'Actuator
springdoc.show-actuator=true
#=======================================================================#
# CONFIGURATION KEYCLOACK												#
#=======================================================================#
keycloak.auth-server-url=https://auth.insee.test/auth
keycloak.realm=agents-insee-interne
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
spring.security.oauth2.resourceserver.jwt.authority-prefix=ROLE_
spring.security.oauth2.resourceserver.jwt.principal-claim-name=preferred_username
spring.security.oauth2.resourceserver.jwt.authorities-claim-name=groups
# URLs autorisees pour faire des requetes HTTP depuis le navigateur
# fr.insee.example.myservice.allowed-origins=*
app.security.allowed-origins=*
#=======================================================================#
# CONFIGURATION SWAGGER												    #
#=======================================================================#
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
# redirection de l'url racine vers swagger
springdoc.swagger-ui.use-root-path=true
# definition du clientId
springdoc.swagger-ui.oauth.clientId=localhost-frontend-minimal
# permet d'avoir du HTTPS dans la liste des serveurs dans la page de swagger
server.forward-headers-strategy=NATIVE
# gestion des scopes coches par defaut
springdoc.swagger-ui.oauth.scopes=role-as-group profile
