---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-gitlab-insee-fr-pull-secret
spec:
  encryptedData:
    .dockerconfigjson: AgAqEssrow5R09+ER4WVyXjGRhm9NGDaSiAmLlYRdRHa5MH/kE5nT7X7i2axzJU7e3voSgz/IhTPNgG1nrPcyiTC+SmPTPz9S149iwZ96dK1yT6UUWKaZW4bNn+c9PbUsgGt4unJN/99FQ2UFDrxutWEdoPa7n+pRy08nyz2qGOzlB12ehvRzsgVMm/uh+9Frl4TwJej6qRbQ7rd/hkDvhhJuwfIFABsm/QxwqFnVWO98Ygbg8TRam2ivSkty6ChT+vR6s5AUx2rYff/RIeC4AlWpn31jbtF0NlWGq7rQD+n7xAZ9n58a4dtgKbAGnWOOqWZQj9wf+vFeB99Hw9B7rfaJLyTafHo+bInn6a93krxOUXwBQOnJ2nFuG73KPtHnaFkMil5vESuOmfPUpZ6fMz1kTCpds0PHYwKUJQKV1Luj2IScm+f5jccJZEyhU1+K3iO1XEw2QBtmkDpQfA/017UlNrYdiFDpu3C5exC9FpqOCUz2WGlwbrUp238HJCWE9ymJZr2OAKyeJVzKx22FcELFb+Yt/aDLwyz6dbScAjSH1casVXFxhC9uS5962IF2V5LMH4LlTVfCB0/50vzVucxIocAdPYZyrtnz81P4ZD+cKwT/jGWCvKHQRtoiWUtp/ymFdfj6Nd6SF3hggdGUPXryzc3gyMtKIZJiA0ZXaW5UAdW9b8A4Ah0evJoJ+xHV85w8ATVTKg+ChxblOwgl4NXz8XpCQkUjw1Oe7DQmERtesrRubY2QcrpiYzN+5j03OB/ZiUzAB3ew4TVKyuSOyEW6EmkT5PFs6nFt0xdPISHOogy/WxvWpnbx1iHW0T4qlSrtAfUErCcUk6291hL0P9sTtvWbr3Y6Rb8OS2hgl1kWRPOjyaLjbRa9N8cdBN3YywlNBjUPtsHTI+SOqgA3L+xXskpAMnAwGSBryDygyqDM2L9OG1bo9jwLaFdTtDPhV3kL1bX/lJacieYifROoKfWWOL/naokA26wD8qEOZGqoGcQ1IdueRQ=
  template:
    metadata:
      name: registry-gitlab-insee-fr-pull-secret
      namespace: crossplane
    type: kubernetes.io/dockerconfigjson
