apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oidc-sugoi
spec:
  encryptedData:
    client_secret: AgAL1piZNP0FVRjDNO3nsadmifPMkVMLV3uDBQlR3U0T7D92XOofdf2Rg0hGDjlW7gd8UIRBEEsHXmGOtglhxZjM1tlD8vykweHtllYEpvAq/vneI4q0LnlTpvJ4otymhguhqvD1IuXQsXbDGUqA70d+Pn/FG7LViicFaolnS5MLEsWrWJmo4qZX14pq1xxdedQbUpFsZHViPOyraaWZ6V9WpUO57OtbN9sPPzZBSOyC9HEGQP2y6BcMk+uDIQQ1gmLNr0YgOMPZQ3yvLpGOm9hun2QbXhArjreH+939k1ENMFSORQw0DQSpeRq1JE5QlvamiEHUrfU8JRcvqepQEurFAETFIs8HINN+Ry+n7BDGc6CIsxcxRjYCnxnUCcWS8rTn8Iia0HVVQ61jqoPZ/8J4YPV6Sxd6w82lIMijKze36yXMjARcuMvTdnTC43m5rXL8vi+Jv0r2AC5OA8m2oNqJ41qQTvLqk0INbhIkEhY+fUhJNqAfnvWcmGYDu4YlURgjnwZpyKfQURBzCVVs4cBLv4DAMKFcPNyEu6pEZ5oOdyJJ84zXlzG50r7XnVSv8mkYkqyWh6+NIroghj3N3XjY4zX8b9cnn3u/2n6LxytyCIuJSlap90czQMxGApttj4Kzqlh4McgTwipcnmcOjZvSiJDTNWWToB3u5ZGhDCY7lc5b3d/wOt2x/Huxj5aCtert/lluVPdQdP/pWTH9ba2FPuyl0JPhHm8YZQKMeGYsUQ==
  template:
    metadata:
      name: oidc-sugoi
    type: Opaque