fr.insee.sndil.starter.role.administrateur=AdministrateurRP_ERA
##SWAGGER
#Client par defaut propose dans la popup de login
springdoc.swagger-ui.oauth.clientId=localhost-frontend

#Non lue par le programme java
fr.insee.sndil.starter.auth.url=https://auth.insee.test/auth
fr.insee.sndil.starter.springdoc.issuer-url-authorization=${fr.insee.sndil.starter.auth.url}/realms/agents-insee-interne/protocol/openid-connect/auth
fr.insee.sndil.starter.springdoc.issuer-url-refresh=${fr.insee.sndil.starter.auth.url}/realms/agents-insee-interne/protocol/openid-connect/token
fr.insee.sndil.starter.springdoc.issuer-url-token=${fr.insee.sndil.starter.auth.url}/realms/agents-insee-interne/protocol/openid-connect/token
fr.insee.sndil.starter.springdoc.issuer-description=Keycloak
fr.insee.sndil.starter.springdoc.contact-name=Le nom de votre contact
fr.insee.sndil.starter.springdoc.contact-email=un-email-fonctionnel@insee.fr
fr.insee.sndil.starter.springdoc.contact-url=https://www.insee.fr/fr/accueil

#URL avec les clefs publiques a utiliser pour valider les tokens
#cf. https://github.com/keycloak/keycloak/blob/main/docs/documentation/securing_apps/topics/oidc/oidc-generic.adoc
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${fr.insee.sndil.starter.auth.url}/realms/agents-insee-interne/protocol/openid-connect/certs

######################### Log des properties #########################
# Plusieurs propriétés commandent l'affichage des properties dans la log (cf. la javadoc de PropertiesLogger).
# La première d'entre elle est fr.insee.properties.log.key.select qui peut prendre les valeurs NONE ALL ou PREFIX(default) :
## 1. fr.insee.properties.log.key.select=NONE => pour desactiver le log des properties
## 2. fr.insee.properties.log.key.select=ALL => pour afficher toutes les properties sans prendre en compte leur prefixe
### - Avec ce parametre, on ignore les prefixes donc on a donc toutes les properties
### - dans ce cas `fr.pwd=toto` sera affichee avec des **** (non affichee par defaut avec PREFIX)
## 3. fr.insee.properties.log.key.select=PREFIX
### - si `fr.insee.properties.log.key.prefixes=fr.pwd,fr.insee`, en mode PREFIX, on va afficher uniquement les properties commencant par fr.insee et fr.pwd
### - si `fr.insee.properties.log.key.prefixes=fr.pwd`, en mode PREFIX, on va afficher uniquement les properties commencant par fr.pwd
