{% if values.exposureProfile === "external" %}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${{ values.appName }}
  namespace: ${{ values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: ${{ values.exposure.publicHost }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${{ values.appName }}
                port:
                  number: 80
  tls:
    - hosts:
        - ${{ values.exposure.publicHost }}
      secretName: ${{ values.appName }}-tls
{% endif %}