default:
  image: gitlab-registry.insee.fr/kubernetes/images/build/maven-jdk:21
  tags:
  - docker

stages:
- 🎨 Formatting
- 📦 Build
- 🔒 Security
- 🐋 Docker
- 🚀 Deploy

variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dhttps.protocols=TLSv1.2
  MAVEN_CLI_OPTS: >-
    --batch-mode --errors --fail-at-end --show-version
  IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"

# Workflow
workflow:
  rules:
  - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

# Build
build:
  stage: build
  script:
  - pnpm install --frozen-lockfile
  - pnpm run lint
  - pnpm run build
  artifacts:
    paths:
    - dist/

# Components
include:
# 🎨 Formatting
- component: gitlab.insee.fr/dsi/analyzer/composants/gitlab-ci-gitleaks-component/scan@1.0.0
  inputs:
    stage: "🎨 Formatting"
    source: "."
    verbose: "true"
    redact: "true"

# 📦 Build
# Maven
- component: $CI_SERVER_FQDN/platform/ci-components/maven/gitlab-ci-maven@1.0.0
  inputs:
    stage: "📦 Build"
    image: docker.io/library/maven:3.9.9-eclipse-temurin-21
    project-dir: "."
    goals: "clean verify"
# SonarQube
- component: $CI_SERVER_FQDN/platform/ci-components/sonar/gitlab-ci-sonar@1.0.0
  inputs:
    stage: "📦 Build"
    image: docker.io/library/maven:3.9.9-eclipse-temurin-21
    sonar-host-url: $SONAR_HOST_URL
    sonar-token: $SONAR_TOKEN

# 🔒 Security
# Détecte les CVE dans les dépendances du pom.xml
- component: $CI_SERVER_FQDN/platform/ci-components/dependency-scanning/gitlab-ci-dependency-scanning@1.0.0
  inputs:
    stage: "🔒 Security"
# Analyse statique
- component: $CI_SERVER_FQDN/platform/ci-components/sast/gitlab-ci-sast@1.0.0
  inputs:
    stage: "🔒 Security"

# 🐋 Docker
- component: gitlab.insee.fr/kubernetes/kubeapp/components/docker/gitlab-ci-docker-lint-component@0.0.2
  inputs:
    stage: "🐋 Docker"
    path_to_dockerfile: "Dockerfile"
- component: gitlab.insee.fr/kubernetes/kubeapp/components/docker/gitlab-ci-docker-build-component@0.0.2
  inputs:
    stage: "🐋 Docker"
    path_to_dockerfile: "Dockerfile" # Optionnel
# Trivy
- component: gitlab.insee.fr/dsi/analyzer/composants/gitlab-ci-trivy-component/scan@2.0.0
  inputs:
    stage: "🐋 Docker"
    fail_on_severity: 'CRITICAL|HIGH'
    rules:
    - when: manual
      allow_failure: true
