apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: testci
  title: java-test-CI-TBC
  description: |
    java-test-CI-TBC - Service Java Spring Boot généré par le Golden Path.
  tags:
  - java
  - spring-boot
  - rest-api
  annotations:
    # GitLab
    gitlab.com/project-slug: platform-engineering/poc/generated/java-test-CI-TBC
    # GitLab CI
    gitlab.com/ci-pipeline: platform-engineering/poc/generated/java-test-CI-TBC
    gitlab.com/instance: gitlab.insee.fr
    # links:
    # - url: https://testci.domaine.insee.fr/swagger-ui.html
    #   title: Swagger UI
    #   icon: api
spec:
  type: service
  lifecycle: experimental
  owner: team-platform
  providesApis:
  - testci-v1
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: testci-v1
  title: java-test-CI-TBC v1
  description: API REST - java-test-CI-TBC.
  tags:
  - rest
  - openapi
spec:
  type: openapi
  lifecycle: experimental
  owner: team-platform
  system: testci # Marche pas ?
  definition:
    $text: ./src/main/resources/openapi/api.yaml
