include:
- project: "platform-engineering/poc/components/tools-gitlab-ci"
  file: "/templates/extract.yml"

- project: "platform-engineering/poc/components/tools-gitlab-ci"
  file: "/templates/validation.yml"

# - project: "platform-engineering/poc/components/kicker"
#   file: "/templates/validation.yml"
# - component: $CI_SERVER_FQDN/to-be-continuous/bash/gitlab-ci-bash@3
#   inputs:
#     shellcheck-files: "*.sh"
# - component: $CI_SERVER_FQDN/to-be-continuous/semantic-release/gitlab-ci-semrel@4
#   inputs:
#     # disable semrel for all synch'd repositories
#     release-disabled: true
#     auto-release-enabled: true
# - component: $CI_SERVER_FQDN/to-be-continuous/gitleaks/gitlab-ci-gitleaks@2

variables:
  GITLAB_CI_FILES: "templates/gitlab-ci-maven.yml"
