spring:
  application:
    name: my-service-java-test17-cond
  config:
    import: optional:file:.env[.properties]

# Actuator / Health checks
management:
  endpoints:
    web:
      exposure:
        include:
        - health
        - info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true

# Serveur 
server:
  port: 8080
  shutdown: graceful
